### ISSUE TITLE
Next Button for the Text Search

### ISSUE THREAD

**Issue by ITN1nja** [OldNESJunkie/uVNCRemoteControl#1]
I'm trying to figure out how to make a next button for the text search field to enable cycling through multiple instances of a search term (such as "Mike", which I have several of in my current hosts list). I don't really know Pure Basic, but I think I'm figuring out the structure and might be able to figure out how to create the feature on my own. If you like the idea and want to implement it before I have the time to figure it out around my regular work, here is the idea. I'm simply planning on shortening the #text_search field by enough to add a button with the text "Next" on it that will go to the next instance of the text found in the hosts list. I don't know how to do that yet, but I'm sure I'll eventually figure it out. If I do and you haven't already implemented this feature yourself, I'll upload the code for your approval if you'd like.

**Comment by OldNESJunkie** [comment]
I like the idea, but I've not had the time myself to implement it or 
figure out how to do it.  If you can figure it out, would be a good 
addition for sure.

Daniel

------ Original Message ------

**Comment by ITN1nja** [comment]
I'll work on it as I have time. I downloaded a demo of PureBasic, but it keeps giving compile errors. I don't know if I just need to purchase a license for API support, or what. Either way, I'll tinker and see what I can do when I can. I'm not really a software engineer by trade, so it will take a bit. 👍

**Comment by OldNESJunkie** [comment]
Lol, I'm not either as the source shows 😋

**Comment by OldNESJunkie** [comment]
Check out the latest release to see the new search function.
