### ISSUE TITLE
Concurrent instances

### ISSUE THREAD

**Issue by ITN1nja** [OldNESJunkie/uVNCRemoteControl#2]
There are cases in which I can use or need multiple remotes session to different clients. Past VNC-based utilities similar to this one that I've used didn't have any mechanism to prevent concurrent instances. Is there a technical reason for the prevention on concurrent instances in this utility? The only issue I ran into in one precursor was an issue of trying to connect two two different hosts before the first host connection was fully set up and multiple sessions would be opened on one of the hosts. 

I am interested in making the concurrent instance check optional, assuming there isn't a technical reason to make it mandatory.

**Comment by OldNESJunkie** [comment]
To be honest I have not tested to see if it would work or not.  Just
comment out the code and test I suppose. I assume you know where the code
is?

**Comment by ITN1nja** [comment]
Yep! I saw the code snippet that looks for a current instance. I figured that I could add a checkbox in the program options that an If statement checks against before running that snippet. I wanted to make sure there wasn't any known technical issues first, though. 

I'm still trying to figure out the search thing, so I'll probably just roll both features into an update on my branch when I figure that out.

**Comment by OldNESJunkie** [comment]
For the search I thought about storing the listview contents and position
in a list, then using the findstring command to parse through with a next
button, but haven't had time to sit down and look at it the past week or
so....  The fill list icon function in the list icon.pbi file creates a
list to fill the gadget from a cab file but it clears the list, thought
about changing it so it doesn't clear the list and using it for the search,
but again time is an issue right now.

Thanks,
Daniel

**Comment by OldNESJunkie** [comment]
EDIT:

Nope, seems to work fine without all the gunk.

**Comment by ITN1nja** [comment]
That's certainly more involved than I was anticipating. I'll have to take a more expansive review of the code. I really haven't looked at the entire code yet, so I don't know how the pass-off to the VNC session is being handled. I was assuming that the close of the VNC session would hand-off the remote host ID for the clean-up procedure or that the process ID was inherently tracked. Yeah, I'll have to think about that more. 

I still don't even have a way to compile my version of code to test yet. I simply haven't bought the PureBasic package or had enough time to compile the opensource version. This is just what I've cobbled together on lunch and breaks so far. I'm kinda learning PureBasic on the go.

**Comment by OldNESJunkie** [comment]
Yeah, that's how I still am even like 12 years after I first picked it up.
😅. There are probably more experienced coders that could rewrite the whole
thing to be better, etc but at least I was able to get it to do what I
needed. 🤷‍♀️

**Comment by OldNESJunkie** [comment]
See below.

**Comment by OldNESJunkie** [comment]
Attached is the source with the hostname file chang and also the 
checkbox in App Options to allow multiple instances if you want to test.



------ Original Message ------

**Comment by OldNESJunkie** [comment]
OK,
I rewrote the connection procedure and added icons to represent connected/not connected remote hosts.  Still using the mutex to only allow one instance of the program, but you can connect to multiple computers and each will highlight to let you know which ones you are connected to.  You can also double-click on a highlighted one to bring up that VNC Viewer.  If you have multiple instances open and choose to right click on the viewer icon in the task bar and close all open windows it will remove from all instances successfully.  Still have some work to do but it's working as-is.  Need to still figure out the next button for searching, I have an idea for that as well I'll try when I have more time.  I uploaded the new code here, but you can get the latest version from my site to test:
http://oldnesjunkie.duckdns.org/software/uVNCRemoteControl.zip

**Comment by OldNESJunkie** [comment]
This should be solved now, if you check the latest download I changed the search feature and was able to add the icons to show which computers you are currently connected to.
